<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <title>Projeto Slim Framework 3</title>

        <link rel="stylesheet" href="<?php echo PATH; ?>/css/estilo.css">
        <link rel=icon href=/favicon.ico sizes="32x32 48x48" type="image/vnd.microsoft.icon">
    </head>
    <body>
        <header id="topo-um">
            <div class="container">
                <h1 class="logo-site">Logo Site</h1>

                <nav id="menu">
                    <ul>
                        <li><a href="<?php PATH; ?>/" alt="home">Home</a></li>
                        <li><a href="<?php PATH; ?>/sobre" alt="sobre">Sobre</a></li>
                        <li><a href="<?php PATH; ?>/contato" alt="contato">Contato</a></li>
                    </ul>
                </nav>
            </div>
        </header>

        <section>
            <div class="container">
