<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h2>Novo Post</h2>

            <div class="panel panel-default">
                <div class="panel-heading">
                    Formulário de cadastro de Post
                </div>

                <div class="panel-body">
                    <form method="post">
                        <div class="form-group">
                            <label for="titulo">Título</label>
                            <input id="titulo" name="titulo" type="text" class="form-control" placeholder="Título">
                        </div>

                        <div class="form-group">
                            <label for="descricao">Descrição</label>
                            <textarea id="descricao" name="descricao" class="form-control" rows="10" placeholder="Descrição"></textarea>
                        </div>

                        <button type="submit" class="btn btn-primary">Cadastrar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
