<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>Posts</h2>

            <a href="<?php echo PATH; ?>/admin/posts/add" class="btn btn-primary btn-lg btn-block">Novo Post</a><br>

            <div class="panel panel-default">
                <div class="panel-heading">
                    Lista de Posts
                </div>

                <div class="panel-body">
                    <table class="table ">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Título</th>
                                <th>Ações</th>
                            </tr>
                        </thead>

                        <tbody>
                            <tr>
                                <td>1</td>
                                <td>Um título qualquer</td>
                                <td>
                                    <a href="#" alt="visualização" class="btn btn-info">Visualizar</a>
                                    <a href="#" alt="editar" class="btn btn-warning">Editar</a>
                                    <a href="#" alt="excluir" class="btn btn-danger">Excluir</a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
